# NOTE: Before deploying to a production environment, please review the documentation -> https://aka.ms/self-hosted-gateway-production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shg2-env
  labels:
    app: shg2
data:
  config.service.endpoint: "apipmshgperf1b.configuration.azure-api.net"
  neighborhood.host: "shg2-instance-discovery"
  runtime.deployment.artifact.source: "Azure Portal"
  runtime.deployment.mechanism: "YAML"
  runtime.deployment.orchestrator.type: "Kubernetes"
  telemetry.logs.std.level: "warn"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shg2
  labels:
    app: shg2
spec:
  replicas: 16
  selector:
    matchLabels:
      app: shg2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: shg2
    spec:
      nodeSelector:
        agentpool: nodepool1
      terminationGracePeriodSeconds: 60
      containers:
      - name: shg2
        image: mcr.microsoft.com/azure-api-management/gateway:v2
        resources:
          requests:
            cpu: "4000m"
            memory: 2Gi
          limits:
            cpu: "4000m"
            memory: 2Gi
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8081
          # Container port used for rate limiting to discover instances
        - name: rate-limit-dc
          protocol: UDP
          containerPort: 4290
          # Container port used for instances to send heartbeats to each other
        - name: dc-heartbeat
          protocol: UDP
          containerPort: 4291
        readinessProbe:
          httpGet:
            path: /status-0123456789abcdef
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: config.service.auth
          valueFrom:
            secretKeyRef:
              name: shg2-token
              key: value
        envFrom:
        - configMapRef:
            name: shg2-env
---
apiVersion: v1
kind: Service
metadata:
  name: shg2-live-traffic
  labels:
    app: shg2
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8081
  selector:
    app: shg2
---
apiVersion: v1
kind: Service
metadata:
  name: shg2-instance-discovery
  labels:
    app: shg2
  annotations:
    azure.apim.kubernetes.io/notes: "Headless service being used for instance discovery of self-hosted gateway"
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: rate-limit-discovery
    port: 4290
    targetPort: rate-limit-dc
    protocol: UDP
  - name: discovery-heartbeat
    port: 4291
    targetPort: dc-heartbeat
    protocol: UDP
  selector:
    app: shg2